version: '3'
services:
  mongo:
    container_name: mongo-cna
    image: mongo:5.0
    restart: always
    volumes: 
      - ./data:/data/db
    ports:
      - '27017:27017'
  api:
    container_name: api-cna
    image: node:14
    working_dir: /usr/src/clean-node-api
    restart: always
    command: bash -c "yarn install --only=prod && yarn debug"
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - '5050:5050'
      - '9222:9222'
    links:
      - mongo